import type { KanbanCardData } from '../components/KanbanCard'

/**
 * Assembles a markdown brief for the agent.
 * Written to ~/.contex/briefs/<card-id>.md before launch.
 * Passed as the first file reference in the launch command.
 */
export function buildAgentBrief(card: KanbanCardData, allCards: KanbanCardData[]): string {
  const lines: string[] = []

  lines.push(`# ${card.title}`)
  lines.push('')

  if (card.description) {
    lines.push(`## Description`)
    lines.push('')
    lines.push(card.description)
    lines.push('')
  }

  lines.push(`## Task`)
  lines.push('')
  lines.push(card.instructions || '_No instructions provided._')
  lines.push('')

  // File context
  if (card.fileRefs.length > 0) {
    lines.push(`## Files`)
    lines.push('')
    for (const f of card.fileRefs) {
      lines.push(`- \`${f}\``)
    }
    lines.push('')
  }

  // Card references
  if (card.cardRefs.length > 0) {
    lines.push(`## Related Tasks`)
    lines.push('')
    for (const ref of card.cardRefs) {
      const linked = allCards.find(c => c.title === ref || c.id === ref)
      if (linked) {
        lines.push(`### ${linked.title}`)
        if (linked.description) lines.push(linked.description)
        if (linked.instructions) lines.push('')
        lines.push(`> ${linked.instructions}`)
        lines.push('')
      } else {
        lines.push(`- ${ref}`)
      }
    }
    lines.push('')
  }

  // Tools
  if (card.tools.length > 0) {
    lines.push(`## Tools Available`)
    lines.push('')
    for (const t of card.tools) {
      lines.push(`- \`@${t}\``)
    }
    lines.push('')
  }

  // Skills & commands
  if (card.skillsAndCommands.length > 0) {
    lines.push(`## Skills & Commands`)
    lines.push('')
    for (const s of card.skillsAndCommands) {
      lines.push(`- \`/${s}\``)
    }
    lines.push('')
  }

  // MCP
  lines.push(`## Canvas Communication`)
  lines.push('')
  lines.push('You are connected to the Contex canvas host via MCP and SSE.')
  lines.push('')
  lines.push(`**Your card ID:** \`${card.id}\` (also available as \`$CARD_ID\` in your environment)`)
  lines.push('')
  lines.push('### MCP Tools')
  lines.push('')
  lines.push('Call these tools to communicate with the canvas:')
  lines.push('')
  lines.push('| Tool | When to call |')
  lines.push('|------|-------------|')
  lines.push('| `card_complete(card_id, summary)` | Task done — moves card to next column. **Required.** |')
  lines.push('| `card_update(card_id, note, status?)` | Progress note — visible on canvas in real time |')
  lines.push('| `card_error(card_id, reason)` | Task failed or blocked |')
  lines.push('| `request_input(card_id, question, options?)` | Ask the operator a question |')
  lines.push('| `canvas_create_tile(type, title?, file_path?, x?, y?)` | Create a new tile on the canvas |')
  lines.push('| `canvas_open_file(path)` | Open a file as a tile |')
  lines.push('| `canvas_pan_to(x, y)` | Pan the canvas to a position |')
  lines.push('| `canvas_list_tiles()` | List all tiles currently on the canvas |')
  lines.push('')
  lines.push('### SSE Stream')
  lines.push('')
  lines.push('You can also stream events directly via HTTP POST:')
  lines.push('```')
  lines.push('POST http://127.0.0.1:$MCP_PORT/push')
  lines.push('Content-Type: application/json')
  lines.push('')
  lines.push(`{ "card_id": "${card.id}", "event": "card_update", "data": { "note": "..." } }`)
  lines.push('```')
  lines.push('')
  lines.push('The canvas subscribes to `GET /events?card_id=global` and renders updates in real-time.')
  lines.push('')

  if (card.mcpServers.length > 0) {
    lines.push('Additional MCP servers:')
    lines.push('')
    for (const s of card.mcpServers) {
      const endpoint = s.url ?? s.cmd ?? ''
      lines.push(`- **${s.name}**: \`${endpoint}\``)
    }
    lines.push('')
  }

  // Completion criteria
  lines.push(`## Completion`)
  lines.push('')
  lines.push('When the task is complete:')
  lines.push('1. Call `card_complete` with your card_id and a concise summary of what was done')
  lines.push('2. The board will automatically move this card to the next column')
  lines.push('3. If you encounter a blocker, call `card_error` instead')
  lines.push('')

  lines.push(`---`)
  lines.push(`_Generated by Contex · ${new Date().toISOString()}_`)

  return lines.join('\n')
}
